### ISSUE TITLE
您好，这个是怎么使用呢

### ISSUE THREAD

**Issue by liqine** [realityone/pppd-netkeeper-rs#2]

**Comment by realityone** [comment]
rustup 加 mips-unknown-linux-musl，编译后用丢到 musl libc 的 openwrt 上，和之前 c 版的一样用就行了。

**Comment by liqine** [comment]
大佬，能帮忙写个详细点的教程吗，，这个没看明白

**Comment by liqine** [comment]
大佬，能帮忙写个详细点的教程吗，，这个没看明白
